USE [master]
GO
/****** Object:  Database [BaseProductos]    Script Date: 12/1/2018 10:11:10 PM ******/
CREATE DATABASE [BaseProductos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BaseProductos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\BaseProductos.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BaseProductos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\BaseProductos_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [BaseProductos] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BaseProductos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BaseProductos] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BaseProductos] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BaseProductos] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BaseProductos] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BaseProductos] SET ARITHABORT OFF 
GO
ALTER DATABASE [BaseProductos] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BaseProductos] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [BaseProductos] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BaseProductos] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BaseProductos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BaseProductos] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BaseProductos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BaseProductos] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BaseProductos] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BaseProductos] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BaseProductos] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BaseProductos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BaseProductos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BaseProductos] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BaseProductos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BaseProductos] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BaseProductos] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BaseProductos] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BaseProductos] SET RECOVERY FULL 
GO
ALTER DATABASE [BaseProductos] SET  MULTI_USER 
GO
ALTER DATABASE [BaseProductos] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BaseProductos] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BaseProductos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BaseProductos] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'BaseProductos', N'ON'
GO
USE [BaseProductos]
GO
/****** Object:  Table [dbo].[Productos]    Script Date: 12/1/2018 10:11:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Productos](
	[codigo] [int] NOT NULL,
	[nombre] [nvarchar](max) NULL,
	[categoria] [nvarchar](max) NULL,
	[preciocosto] [decimal](18, 2) NULL,
	[margen] [float] NULL,
	[iva] [float] NULL,
	[preciobruto] [decimal](18, 2) NULL,
	[precioventa] [decimal](18, 2) NULL,
 CONSTRAINT [PK_Productos] PRIMARY KEY CLUSTERED 
(
	[codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [BaseProductos] SET  READ_WRITE 
GO
